In [1]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
sample_array=np.array([1,2,3,4])

In [4]:
sample_array

array([1, 2, 3, 4])

In [5]:
sample_array_2=np.array([[1,2],[3,4]])

In [6]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [7]:
sample_tensor_3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [8]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
#dimension

In [10]:
#0-d array(scalar) 5
# 1-d array(vector) [1,2,3,4]
# 2-d array(matrix) [rows,columns)
# 3-d array(tensor) (page,row,column)

In [12]:
sample_array=np.array([[1,2,3],[4,5,6]])

In [13]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
sample_array.shape

(2, 3)

In [15]:
#dimensions

In [16]:
sample_array.ndim

2

In [17]:
# total elements

In [18]:
sample_array.size

6

In [19]:
sample_array.dtype

dtype('int64')

In [22]:
sample_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [23]:
sample_array.shape

(2, 2, 2)

In [24]:
sample_array.ndim

3

In [25]:
sample_array.size

8

In [26]:
sample_array.dtype

dtype('int64')

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [32]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
sample_array=np.array([10,20,30,40])


In [35]:
sample_array

array([10, 20, 30, 40])

In [36]:
sample_array[0]

np.int64(10)

In [37]:
sample_array[2]

np.int64(30)

In [38]:
sample_array[-1]

np.int64(40)

In [39]:
sample_array[1:3]

array([20, 30])

In [40]:
a=np.array([1,2,3])

In [41]:
b=np.array([4,5,6])

In [42]:
a+b

array([5, 7, 9])

In [43]:
a-b

array([-3, -3, -3])

In [44]:
a*b

array([ 4, 10, 18])

In [45]:
a/b

array([0.25, 0.4 , 0.5 ])

In [46]:
sample_array=np.array([1,4,9])

In [47]:
sample_array

array([1, 4, 9])

In [48]:
np.sqrt(sample_array)


array([1., 2., 3.])

In [49]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [50]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [51]:
#statistical functions

In [52]:
sample_array=np.array([1,2,3,4,5])

In [53]:
sample_array

array([1, 2, 3, 4, 5])

In [54]:
np.mean(sample_array)

np.float64(3.0)

In [55]:
np.median(sample_array)

np.float64(3.0)

In [58]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [59]:
np.min(sample_array)

np.int64(1)

In [60]:
np.max(sample_array)

np.int64(5)

In [61]:
#reshaping array

In [65]:
sample_array=np.arange(0,6,1)

In [66]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [67]:
reshaped=sample_array.reshape(2,3)

In [69]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
#Flatenning

In [72]:
sample_array=np.array([[1,2],[3,4]])

In [73]:
sample_array

array([[1, 2],
       [3, 4]])

In [74]:
sample_array.flatten()

array([1, 2, 3, 4])

In [77]:
sample_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [78]:
sample_array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
#joining arrays

In [83]:
a=np.array([1,2,3,4])


In [84]:
b=np.array([5,6,7,8])

In [85]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
#Splitting arrays

In [87]:
sample_array=np.array([1,2,3,4])

In [88]:
sample_array

array([1, 2, 3, 4])

In [89]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [90]:
#Random module

In [91]:
np.random.rand(3)

array([0.87446153, 0.27758395, 0.92503569])

In [92]:
np.random.randint(1,10,5)

array([5, 2, 5, 1, 4], dtype=int32)

In [93]:
#Axis concept

In [94]:
a=np.array([[1,2],[3,4]])

In [95]:
np.sum(a,axis=0)

array([4, 6])

In [96]:
np.sum(a,axis=1)

array([3, 7])

In [97]:
#Nan & Missing Values

In [98]:
sample_array=np.array([1,np.nan,3])

In [99]:
sample_array

array([ 1., nan,  3.])

In [100]:
np.isnan(sample_array)

array([False,  True, False])

In [101]:
#create 2 numpy arrays and perform element wise addition ,subtraction,multiplication and modulus operations

In [102]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.add(a,b)

array([ 6,  8, 10, 12])

In [104]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [107]:
a*b

array([ 5, 12, 21, 32])

In [109]:
a%b

array([1, 2, 3, 4])

In [110]:
import pandas as pd

In [111]:
s=pd.Series([10,20,30])

In [112]:
s

0    10
1    20
2    30
dtype: int64

In [113]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [114]:
s

a    10
b    20
c    30
dtype: int64

In [116]:
s=pd.Series(["akshata",18,95],index=['name','age','marks'])

In [117]:
s

name     akshata
age           18
marks         95
dtype: object

form dictionary

In [118]:
data={'name':'rahul','age':25,'Marks':90}

In [119]:
s=pd.Series(data)

In [120]:
s

name     rahul
age         25
Marks       90
dtype: object

In [121]:
s=pd.Series(5,index=[0,1,2,3])

In [122]:
s

0    5
1    5
2    5
3    5
dtype: int64

In [123]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [124]:
s

a    10
b    20
c    30
dtype: int64

In [125]:
s.values

array([10, 20, 30])

In [126]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [127]:
s.dtype

dtype('int64')

In [128]:
s.shape

(3,)

data manipulation

In [129]:
s=pd.Series([1,2,3])

In [130]:
s*3

0    3
1    6
2    9
dtype: int64

handling missing values

In [132]:
s=pd.Series([1,None,3])

In [133]:
s

0    1.0
1    NaN
2    3.0
dtype: float64

s.isnull()

In [135]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [137]:
s.fillna(0)

0    1.0
1    0.0
2    3.0
dtype: float64

indexing

In [138]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [139]:
s['a']

np.int64(10)

In [140]:
s['c']

np.int64(30)