In [2]:
# 1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
# TypeError separately, printing an appropriate message for each. Use a finally block to print
# 'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
# string input.
def safe_divide(a,b):
    try:
        result=a/b
        print("result:",result)
    except ZeroDivisionError:
        print("error:division by zero is not allowed")
    except TypeError:
        print("error:Invalid data type.please enter numbers only")
    finally:
        print("Operation attempted")
safe_divide(10,2)
safe_divide(10,0)
safe_divide(10,'a')


result: 5.0
Operation attempted
error:division by zero is not allowed
Operation attempted
error:Invalid data type.please enter numbers only
Operation attempted


In [4]:
# 2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
# define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
# calling block and print a user-friendly message. Test it with at least 3 different values.
class InvalidAgeError(Exception):
    pass
def validate_age(age):
    if age<0 or age>120:
        raise InvalidAgeError("age should be between 0 and 120")
    print("valid age:",age)
ages=[-25,45,130]
for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print("invalid age error:",e)
    

invalid age error: age should be between 0 and 120
valid age: 45
invalid age error: age should be between 0 and 120


In [6]:
# 3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
# e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
# a single try block using multiple except clauses:
# a) ValueError if the input is not a number.
# b) ZeroDivisionError if the input is zero.
# c) A generic Exception as a catch-all for anything else.
# Print the result if successful, otherwise print which error occurred
user_inputs=['10','abc','0','5']
for user_input in user_inputs:
    try:
        num=int(user_input)
        result=100/num
        print("result:",result)
    except ValueError:
        print("ValueError:input is not a valid number")
    except ZeroDivisionError:
        print("ZeroDivisionError:cannot divide by zero")
    except Exception as e:
        print("Exception:",e)
        

result: 10.0
ValueError:input is not a valid number
ZeroDivisionError:cannot divide by zero
result: 20.0


In [1]:
# 4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
# a) Reshape it into a 4x5 2D array.
# b) Print the sum of each row and each column.
# c) Extract all elements greater than 10 using boolean indexing.
# d) Replace all even numbers in the array with -1.
import numpy as np
arr=np.arange(1,21)
print("original array:")
print(arr)
arr_2d=arr.reshape(4,5)
print("\n4x5 array")
print(arr_2d)
print("\nsum of each row:")
print(arr_2d.sum(axis=1))
print("\nsum of each column")
print(arr_2d.sum(axis=0))
print("\nElements greater than 10:")
print(arr[arr>10])
arr[arr%2==0]=-1
print("\narray after replacing even numbers with -1:")
print(arr)


original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

4x5 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

sum of each row:
[15 40 65 90]

sum of each column
[34 38 42 46 50]

Elements greater than 10:
[11 12 13 14 15 16 17 18 19 20]

array after replacing even numbers with -1:
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [3]:
# 5. Create two NumPy arrays A and B as shown below and perform:
# A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
# a) Element-wise addition, subtraction, and multiplication.
# b) Matrix multiplication using np.dot() or the @ operator.
# c) Transpose of A.
# d) The determinant and inverse of A using np.linalg.
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("\nelement-wise addition:")
print(A+B)
print("\nelement-wise subtraction:")
print(A-B)
print("\nelement-wise multiplication:")
print(A*B)
print("\nMatrix multiplication:")
print(np.dot(A,B))
print("\nTranspose of A:")
print(A.T)
print("\ndeterminant of A:")
print(np.linalg.det(A))
print("\ninverse of A:")
print(np.linalg.inv(A))


element-wise addition:
[[ 6  8]
 [10 12]]

element-wise subtraction:
[[-4 -4]
 [-4 -4]]

element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

determinant of A:
-2.0000000000000004

inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
# 6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
# (set a seed of 42 for reproducibility). Then:
# a) Find the mean, median, standard deviation, min, and max.
# b) Sort the array in descending order.
# c) Find the indices of the 3 largest values using np.argsort().
# d) Normalize the array so all values lie between 0 and 1.
import numpy as np
np.random.seed(42)
arr=np.random.randint(1,101,15)
print("original array:")
print(arr)
print("\nMean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard deviation:",np.std(arr))
print("Min:",np.min(arr))
print("Max:",np.max(arr))
print("\nArray in Descending order:")
print(np.sort(arr)[::-1])
print("\nIndices of the 3 largest values:")
print(np.argsort(arr)[-3:])
normalized=(arr-np.min(arr))/(np.max(arr)-np.min(arr))
print("\nNormalized array:")
print(normalized)

original array:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

Mean: 58.06666666666667
Median: 72.0
Standard deviation: 31.4843170836247
Min: 3
Max: 100

Array in Descending order:
[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

Indices of the 3 largest values:
[10  1 11]

Normalized array:
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


In [8]:
# 7. Create a Pandas DataFrame from the dictionary below and perform the following:
# data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
# 25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
# Science"], "Score": [88, 92, 79, 95, 67], }
# a) Display the first 3 rows and the data types of each column.
# b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
# c) Sort the DataFrame by Score in descending order.
# d) Filter rows where Department is 'AI'.
import pandas as pd
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
         "Age": [23, 21,25, 22, 24],
         "Department": ["AI", "Data Science", "AI", "Web Dev", "DataScience"],
         "Score": [88, 92, 79, 95, 67], }
df=pd.DataFrame(data)
print("First three rows:")
print(df.head(3))
print("\ndata types")
print(df.dtypes)
grades=[]
for score in df["Score"]:
    if score>=90:
        grades.append("A")
    elif score>=75:
        grades.append("B")
    else:
        grades.append("C")
df["Grade"]=grades
print("\nDataframe with grades:")
print(df)
print("\nsorted by score(descending):")
print(df.sort_values(by="Score",ascending=False))
print("\nStudents from AI department:")
print(df[df["Department"]=="AI"])


First three rows:
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

data types
Name          object
Age            int64
Department    object
Score          int64
dtype: object

Dataframe with grades:
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24   DataScience     67     C

sorted by score(descending):
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24   DataScience     67     C

Students from AI department:
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [1]:
# 8. Using the same DataFrame from Q7:
# a) Group by Department and find the average Score for each.
# b) Find the row with the highest Score using idxmax().
# c) Rename the column Score to Marks.
# d) Drop the Age column and display the resulting DataFrame.
import pandas as pd
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
         "Age": [23, 21,25, 22, 24],
         "Department": ["AI", "Data Science", "AI", "Web Dev", "DataScience"],
         "Score": [88, 92, 79, 95, 67], }
df=pd.DataFrame(data)
print("\nAverage score by department:")
print(df.groupby("Department")["Score"].mean())
print("\nRow with highest score:")
print(df.loc[df["Score"].idxmax()])
df.rename(columns={"Score":"Marks"},inplace=True)
print("\nDataFrame after renaming:")
print(df)
df.drop("Age",axis=1,inplace=True)
print("\nDataFrame after dropping age column:")
print(df)


Average score by department:
Department
AI              83.5
Data Science    92.0
DataScience     67.0
Web Dev         95.0
Name: Score, dtype: float64

Row with highest score:
Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

DataFrame after renaming:
    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24   DataScience     67

DataFrame after dropping age column:
    Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil   DataScience     67


In [3]:
# 9. Create a DataFrame with some missing values as shown below and handle them:
# import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
# "Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
# np.nan, 30, 20], }
# a) Check the number of missing values in each column using isnull().sum().
# b) Fill missing Price values with the column mean.
# c) Drop rows where Stock is still missing.
# d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index
import numpy as np
import pandas as pd
data = { "Product": ["Pen", "Notebook", "Eraser","Sharpener", "Ruler"],
         "Price": [10, np.nan, 5, 8, np.nan],
         "Stock": [100, 50,np.nan, 30, 20], }
df=pd.DataFrame(data)
print("number of missing values in each column")
print(df.isnull().sum())
df['Price'].fillna(df['Price'].mean(),inplace=True)
print("\nmissing Price values with column mean")
print(df)
df.dropna(subset=["Stock"],inplace=True)
print("\nDataFrame after dropping rows where stock are missing:")
print(df)
df.to_csv("cleaned_products.csv",index=False)
print("\ndata saved successfully to cleaned_products.csv")


number of missing values in each column
Product    0
Price      2
Stock      1
dtype: int64

missing Price values with column mean
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

DataFrame after dropping rows where stock are missing:
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

data saved successfully to cleaned_products.csv


C:\Users\admin\AppData\Local\Temp\ipykernel_7892\2707205190.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(),inplace=True)


In [4]:
# 10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
# a) Print its shape and column names.
# b) Add a new column Total_Value as Price multiplied by Stock.
# c) Use describe() to print summary statistics of the numeric columns.
# d) Wrap the file reading step in a try-except block to handle the case where the file does not
# exist (FileNotFoundError).
import pandas as pd
try:
    df=pd.read_csv("cleaned_products.csv")
    print("shape of dataframe:")
    print(df.shape)
    print("\ncolumn names:")
    print(df.columns)
    df["Total_value"]=df["Price"]*df["Stock"]
    print("\nDataFrame after Total_Values column:")
    print(df)
    print("\nsummary statistics of the numeric columns:")
    print(df.describe())
except FileNotFoundError:
    print("\nerror:cleaned_products.csv file does not exist")
    



shape of dataframe:
(4, 3)

column names:
Index(['Product', 'Price', 'Stock'], dtype='object')

DataFrame after Total_Values column:
     Product      Price  Stock  Total_value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

summary statistics of the numeric columns:
           Price       Stock  Total_value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
